version: 2.1

orbs:
  node: circleci/node@4.0.0

workflows:
  build_test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 14.16.1
      - build_docker_image:
          requires:
            - node/test

jobs:
  build_docker_image:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      # disabled because it is too expensive.
      # - setup_remote_docker:
      # docker_layer_caching: true
      - run:
          name: Set up tag
          command: echo "export TAG=0.1.$CIRCLE_SHA1" >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build -f Dockerfile.dev -t frontend.dev:$TAG .
