version: 2.1

jobs:
  testnbuild:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: "Run Jest tests"
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          destination: coverage
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - run: ls
      - attach_workspace:
          at: ./
      - run:
          name: Install aws cli through python to always get the latest verison
          command: |
            apk add python3 py-pip
            pip3 install awscli --upgrade
      - run:
          name: Remove existing build and deploy new build to aws s3 bucket.
          # 24 hour cache for service-worker.js and index.html to save money. Other files are cached one year (31536000 seconds).
          command: |
            aws s3 sync ./build s3://www.markz-employer-tracker.net --exclude index.html --exclude service-worker.js --acl public-read --cache-control max-age=31536000,public --delete 
            aws s3 sync ./build s3://www.markz-employer-tracker.net --include index.html --include service-worker.js --acl public-read --cache-control max-age=86400,public

workflows:
  test-build-deploy:
    jobs:
      - testnbuild
      - deploy:
          requires:
            - testnbuild
          # filters:
          #   branches:
          #     only: master
