version: 2.1

jobs:
  test:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: "Run Jest tests"
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          destination: coverage

  build:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - restore_cache: # at this stage we are 100% sure the saved cache is up to date.
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install aws cli through python to always get the latest verison
          command: |
            apk add python3 py-pip
            pip3 install awscli --upgrade
      - run:
          name: install docker cli inside the alpine container...
          command: |
            apk add --update docker openrc
            rc-update add docker boot
      # - run:
      #     name: Deploy build files to aws s3 bucket.
      #     command: aws s3 sync ./build s3://react-frontend-circleci

      - run:
          name: Login to aws-ecr
          command: aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 236766577229.dkr.ecr.ap-southeast-2.amazonaws.com
      - run:
          name: build and push image to the ecr repo
          command: |
            docker build -f Dockerfile.prod -t portfolio-frontend .
            docker tag portfolio-frontend:latest 236766577229.dkr.ecr.ap-southeast-2.amazonaws.com/portfolio-frontend:latest
            docker push 236766577229.dkr.ecr.ap-southeast-2.amazonaws.com/portfolio-frontend:latest

workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          # branches:
          #   only:
          #     - master
