version: 2.1
name: frontend
jobs:
  unit-tests:
      docker: 
        - image: circleci/node@14.16.1
      working_directory: ~/frontend
      steps:
        - run: npm install
        - run: npm test