version: 2.1

jobs:
  test:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest tests"
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage/lcov-report/tests
          destination: coverage

  build-n-deploy:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - run: npm run build
      - run:
          name: Install aws cli through python to always get the latest verison
          command: |
            apk add python3 py-pip
            pip3 install awscli --upgrade
            aws --version
      - run:
          name: Deploy build files to aws s3 bucket.
          command: aws s3 sync ./build s3://react-frontend-circleci

workflows:
  test-build-deploy:
    jobs:
      - test
      - build-n-deploy:
          requires:
            - test
