version: 2.1

jobs:
  test_build_deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install AWS CLI through python to always get the latest version of aws cli :)
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: npm install
      - run:
          name: "Run Jest tests and Collect Coverage"
          command: npm test
      - store_artifacts:
          path: coverage
      - run: npm run build
      - run:
          name: Deploy build files to aws s3 bucket.
          command: aws s3 sync ./build s3://react-frontend-circleci

workflows:
  deploy-to-s3:
    jobs:
      - test_build_deploy
