version: 2.1

jobs:
  test:
    docker:
      - image: node:14.16.1-alpine

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: "Run Jest tests"
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          destination: coverage

  build:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - restore_cache: # at this stage we are 100% sure the saved cache is up to date.
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: /root/project
          paths:
            - build

  deploy:
    docker:
      - image: node:14.16.1-alpine
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: root/project/
      - run:
          name: Install aws cli through python to always get the latest verison
          command: |
            apk add python3 py-pip
            pip3 install awscli --upgrade
            aws --version
      - run:
          name: Deploy build files to aws s3 bucket.
          command: aws s3 sync ./build s3://react-frontend-circleci

workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
